//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeStayWeb.Models
{
    using System;
    using System.Collections.Generic;

    public partial class DatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatPhong()
        {
            this.ThanhToans = new HashSet<ThanhToan>();
        }

        public int IDDP { get; set; }
        public Nullable<int> IDKH { get; set; }
        public Nullable<int> IDPhong { get; set; }
        public System.DateTime NgayDat { get; set; }
        public System.DateTime NgayCheckIn { get; set; }
        public System.DateTime NgayCheckOut { get; set; }
        public string TrangThaiDatPhong { get; set; }

        public virtual KhachHang KhachHang { get; set; }
        public virtual Phong Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}