//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeStayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int IDThanhToan { get; set; }
        public Nullable<int> IDDP { get; set; }
        public Nullable<int> IDNV { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public decimal Sotien { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
